config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"

  resources :books
  resources :users, only: [:show, :edit, :update ,:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/home/about" => "homes#about", as: "about"
  get 'users' => 'users#index'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete '/books' => 'books#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy

         validates :name,  length: { minimum: 2, maximum: 20}, uniqueness: true
         validates :introduction,length: { maximum: 50}


         has_one_attached :profile_image

  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 #ここから追加
	 before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
	     user_path(current_user.id)
	end

    def after_sign_out_path_for(resource)
	      root_path
    end

  # 下記を追加

 protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
     before_action :authenticate_user!
     before_action :ensure_current_user, {only: [:edit,:update,:destroy]}
     

	def create
        @user = current_user
		    @book = Book.new(book_params)
        @book.user_id = (current_user.id)
	    if @book.save
        flash[:notice] = "You have creatad book successfully."
		    redirect_to  book_path(@book.id)
        # redirect_to "/books/#{@book.id}"
        else
        @books = Book.all
        flash[:notice] = ' errors prohibited this obj from being saved:'
        render "index"
        end
	end

    def show
        @user = current_user
    	@book = Book.find(params[:id])
    	@book_new = Book.new
    	@user = @book.user
    	
    	
    end

    def index
        @user = current_user
        @books = Book.all
        @book = Book.new
        
    end

    def edit
    	@book = Book.find(params[:id])
    end


    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
        flash[:notice] = "You have creatad book successfully."
        redirect_to  book_path(@book.id)

        else
        @books = Book.all
         flash[:notice]= ' errors prohibited this obj from being saved:'
        render "edit"
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to "/books"
    end

	private

    def book_params
        params.require(:book).permit(:title, :body)
    end

     def user_params
        params.require(:user).permit(:name,:profile_image,:introduction)
     end
 
     def  ensure_current_user
      @book = Book.find(params[:id])
      if @book.user_id != current_user.id
        redirect_to books_path
      end
     end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_action :authenticate_user!
     #(ログインしていない状態で他のページに遷移しようとした場合、ログインページに繊維する)
     before_action :ensure_current_user, {only: [:edit,:update,:destroy]}
     #(ログインユーザー以外の情報を遷移しようとした時に制限をかける)



    def new
        @book = Book.new
    end




    def show
	    @book = Book.new
        @user = User.find(params[:id])
        @books = @user.books


    end

    def new
        @user = User.new(user_params)
        if @user.save
         redirect_to  user_path(current_user.id)#成功の場合
        else
         render "users/sign_up"#失敗の場合
        end
    end

    def edit
       @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
    end






    def index
      @users =User.all
      @books = Book.all
      @book = Book.new
      @user = current_user



    end





    def update
        @user = User.find(params[:id])
      if  @user.update(user_params)
        flash[:notice] = "You have updated user successfully."

        redirect_to "/users/#{current_user.id}"
      else
        flash[:notice] = " errors prohibited this obj from being save. name is too short (minimum is 2 characters)"
        render :edit

      end
    end







   private


    def book_params
        params.require(:book).permit(:title, :body)
    end

    def user_params
        params.require(:user).permit(:name,:profile_image,:introduction)
    end

    def  ensure_current_user
        @user = User.find(params[:id])
     if @user.id != current_user.id
        redirect_to user_path(current_user.id)

     end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book' %>
  
  <%= link_to "Show",book_path(@book.id)%>
  <%= link_to "Back",books_path %>
  
<% end %>

app/views/books/index.html.erb
<div class="container">
 
  <% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>


<div class="row">
 <div class= "col-md-3">
   <h2>User info</h2>
   <%= image_tag @user.get_profile_image(100,100) , class:"mt-3 rounded-circle"; %>
   
   
    <%= link_to edit_user_path(@user.id), class:"nav-link text-dark" do %>
    <i class= "fas fa-user-cog"></i>
    
   
    <% end %>
   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %>








        <!-- form_for部分 -->
   <%= form_for(@book,  url: books_path) do |f| %>
    <h2>New book</h2>
    <h4>Title</h4>
    <%= f.text_field :title,class: "col-xs-12" %>

    <h4>Opinion</h4>
     <%= f.text_field :body,class: "col-xs-12" %>
    <nav>
    <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    </nav>
    <% end %>

  </div>





    <div class=  "offset-md-1 col-md-8">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>

      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      </tr>





      <% @books.each do |book| %>
      <tr>
       <td>
       <%= link_to user_path(book.user.id) do %>
       <%= image_tag book.user.get_profile_image(100,100) ,  fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
       <% end %>
       </td>

      <td><%=link_to book.title, book_path(book.id)%></td>
      <td><%=link_to book.body %></td>
      </tr>
      <% end %>
      </table>
    </div>
    </div>

</div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @book do |f| %>
    
    <h4>タイトル</h4>
      <%= f.text_field :title %>
    <h4>内容</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>
<div class="container">
 <div class="row">
 <div class= "col-md-3">
  <h2>User info</h2>
   <%= image_tag @user.get_profile_image(100,100) ,  fallback: "no_image.jpg" ,format: 'no_image.jpg' %>

   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %>
   
   
    <%= link_to edit_user_path(@user.id), class:"nav-link text-dark" do %>
    <i class= "fas fa-user-cog"></i>
    
  
   <% end %>




        <!-- form_for部分 -->
   <%= form_for(@book_new,  url: books_path)  do |f| %>


    <h2>New book</h2>
    <h4>Title</h4>
     <%= f.text_field :title,class: "col-xs-12" %>
    <h4>Opinion</h4>
    <%= f.text_field :body,class: "col-xs-12" %>
    <nav>
     <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    </nav>
    <% end %>
  </div>



  <div class=  "offset-md-1 col-md-8">
    <h2>Book detail</h2>
    <table class='table' >
    <tr>
    <td>
      <%= link_to user_path(@book.user_id) do %>
        <%= image_tag @book.user.get_profile_image(100,100) , fallback: "no_image.jpg",format: 'no_image.jpg' %>
         <nav>
           <%= @book.user.name %>
         </nav>
       <% end %>
    </td>
    


    <td><%= link_to @book.title %></td>
    <td><%= @book.body %></td>
    <% if @book.user_id == current_user.id %>
    <td><%= link_to"Edit", edit_book_path(@book.id),class:"btn-sm btn-success" %></td>
    <td><%= link_to "Destroy", book_path(@book.id), class:"btn-sm btn-danger destroy(@book.id)", method: :delete,data: {confirm: "削除しますか？"} %></td>
    <% end %>
    </tr>
    </table>
  </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="box">
<title>Bookers2</title>

<h1>Welcome to<i class= "fas fa-book"></i>Bookers!</h1>

</div>

app/views/homes/top.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class= "fas fa-book"></i>Bookers2!!</h1>
      <p>In  <i class= "fas fa-book"></i>Bookers2,</p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>
      
      

app/views/layouts/application.html.erb
<div class="box">


<!DOCTYPE html>
<html>
<head>
  
 
<title>Bookers2</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>











<body>
  <header class="navbar navbar-expand-lg navbar-dark text-white bg-dark">
    <div class="container">
      <nav class='nav navbar-nav navbar-left' >
        <div class="box">
          <%= link_to root_path, class:"nav-link text-light" do %>
          <span class="glyphicon glyphicon-user" aria-hidden="true">Bookers2</span>
          <% end %>
        </div>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <p>
              <i class= "fas fa-home"></i>
              <%= link_to "Home", user_path(current_user),  class:"nav-link text-light"  %>
              </p>
            
            </li>
            
            <li>
              <i class= "fas fa-users"></i>
              <%= link_to "Users", users_path, class:"nav-link text-light"  %>
            
            
            </li>
            
            <li>
              <i class= "fas fa-book-open"></i>
              <%= link_to "Books", books_path, class:"nav-link text-light"  %>
            
            
            </li>
            <li>
              <i class= "fas fa-sign-out-alt"></i>
              <%= link_to "Log out",destroy_user_session_path, method: :delete,  class:"nav-link text-light"  %>
              
              
            </li>

          <% else %>
            <li>
              <i class= "fas fa-home"></i>
              <%= link_to"Home",root_path ,class:"nav-link text-light"  %>
           
            
            </li>
            <li>
              <i class= "fas fa-link"></i>
              <%= link_to "About",about_path, class:"nav-link text-light"  %>
                
                
            </li>
            <li>
              <i class="fas fa-user-plus"></i>
              <%= link_to "Sign up",new_user_registration_path, class:"nav-link text-light"  %>
                
                
              </li>
            <li>
              <i class="fas fa-sign-in-alt"></i>
              <%= link_to "Log in",new_user_session_path, class:"nav-link text-light"  %>
                
                
            </li>
          <% end %>
        </<ul>
      </nav>
    </div>
  </header>

  <div class= "body">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
  </div>

 <%= yield %>
 


  <footer>
    <div class='container'>
      <div class='row'>
        <div class='offset-md-6'></div>
       <div class='col-md-6'><p>CopyRight Infratop.inc</p></div> 
      </div>
    </div>
  </footer>
  </body>
  </div>
</html>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"紹介"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
 <% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>


<div class="container">


<div class="row">
 <div class= "col-md-3">
   <h2>User info</h2>
   <%= image_tag @user.get_profile_image(100,100) , class:"mt-3 rounded-circle" %>




    <%= link_to edit_user_path(@user.id), class:"nav-link text-dark" do %>
    <i class= "fas fa-user-cog"></i>




    <% end %>
   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %>








        <!-- form_for部分 -->
   <%= form_for(@book,  url: books_path) do |f| %>
    <h2>New book</h2>
    <h4>Title</h4>
    <%= f.text_field :title,class: "col-xs-12" %>

    <h4>Opinion</h4>
     <%= f.text_field :body,class: "col-xs-12" %>
    <nav>
    <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    </nav>
    <% end %>

  </div>



<div class=  "offset-md-1 col-md-8">
<h2>Users</h2>
      <table class='table table-hover table-inverse'>

      <tr>
      <th></th>
      <th>Name</th>
      <th>introduction</th>
      <th colspan="3"></th>
      </tr>

<% @users.each do |user| %>

<tr>
   <td>
    <%= image_tag user.get_profile_image(100,100), fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
   </td>

    <td><%= user.name %></td>


  <td><%= user.introduction %></td>
  <td>
  <%= link_to"Show",user_path(user.id) %></td>
  </tr>
  <% end %>
  </table>

  </div>


  </div>
  </div>

app/views/users/show.html.erb
<% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>


<div class="container">


<div class="row">
 <div class= "col-md-3">
   <h2>User info</h2>
   <%= image_tag @user.get_profile_image(100,100) , class:"mt-3 rounded-circle"; %>
   
   <li>
    <%= link_to edit_user_path(@user.id), class:"nav-link text-dark" do %>
    <i class= "fas fa-user-cog"></i>
    
   </li>
   <% end %>

   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %>








        <!-- form_for部分 -->
   <%= form_for(@book,  url: books_path) do |f| %>
    <h2>New book</h2>
    <h4>Title</h4>
    <%= f.text_field :title,class: "col-xs-12" %>

    <h4>Opinion</h4>
     <%= f.text_field :body,class: "col-xs-12" %>
    <nav>
    <%= f.submit 'Create Book',class: "col-xs-12 btn btn-primary" %>
    </nav>
    <% end %>

  </div>





    <div class=  "offset-md-1 col-md-8">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>

      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      </tr>


<!-- ユーザーの投稿一覧 -->

<% @books.each do |book| %>

<tr>
  <%= link_to user_path(@user.id) do %>
  <td><%= image_tag @user.get_profile_image(100,100), fallback: "no_image.jpg",format: 'no_image.jpg' %></td>
  
  
  <% end %>
  

  <td><%=link_to book.title, book_path(book) %></td>
  <td><%= book.body %></td>
  </tr>
  
  <% end %>
  </table>
  
    </div>
    
  
</div>
</div>